version: "3.8"
services:

    # PHP Service
    php:
        tty: true
        container_name: php
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - database
        networks:
            - victonet

    # Database Server
    database:
        container_name: database
        image: mysql:8.0
        ports:
            -   3307:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=1
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - victonet
    web:
        image: nginx:latest
        ports:
            - 8001:8000
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www
        restart: unless-stopped
        tty: true
        depends_on:
            - php
        networks:
            - victonet
volumes:
    db-data: ~
networks:
  victonet:
    driver: bridge
